### ISSUE TITLE
bzip2/1.0.8: ERROR: Package '71b4e3715d64cdeddc572f4acceb205c692397cb' build failed

### ISSUE THREAD

**Issue by pointer** [memsharded/example-boost-poco#3]

**Comment by memsharded** [comment]
Hi @pointer 

You may have landed here from an old link or something. You shouldn't get here from the updated version of the docs or packages in ConanCenter, but let me know if I can help somehow.

**Comment by pointer** [comment]
Ok ....thanks

**Comment by memsharded** [comment]
This happens when:

- You installed some packages from ConanCenter.
- You removed the ConanCenter remote (``conan remote remove conan-center``)
- Even if you add it later, the association of packages to the remotes is lost
- Then, at some point expat package needs to get the sources from the remote, they are not downloaded if they are not needed, only when necessary to build from source, or you need to upload them to another remote (to be complete)
- As the expat recipe lost the reference to the remote, it fails

Possible solutions:
- remove the expat package from the cache and have it downloaded again from ConanCenter
- Manually define ``conan remote add_ref expat.... conan-center`` to re-define the connection, and retry

**Comment by pointer** [comment]
ok...thanks

**Comment by memsharded** [comment]
All good then with this issue @pointer? Did you manage to get it working?

**Comment by pointer** [comment]
i’m dismantling everything and redoing from start....keep you
posted....thank you for your feedback
